EducationSystemKZ/EducationSystemKZ_Azure/Controllers/ExpensesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EducationSystemKZ_Azure.Models;

namespace EducationSystemKZ_Azure.Controllers
{
    public class ExpensesController : Controller
    {
        private zheminDBEntities db = new zheminDBEntities();


        // Index
        public ActionResult Index()
        {
            return View();
        }

        // GET: Expenses
        public ActionResult GetAll()
        {
            var expenses = db.Expenses.Include(e => e.Staff);
            return View(expenses.ToList());
        }

        // GET: Expenses/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Expense expense = db.Expenses.Find(id);
            if (expense == null)
            {
                return HttpNotFound();
            }
            return View(expense);
        }

        // GET: Expenses/Create
        public ActionResult Create()
        {
            ViewBag.StaffId = new SelectList(db.Staffs, "Id", "Name");
            return View();
        }

        // POST: Expenses/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Description,Amount,DateTime,StaffId")] Expense expense)
        {
            
            if (ModelState.IsValid)
            {
                expense.DateTime = DateTime.Now;
                db.Expenses.Add(expense);
                db.SaveChanges();
                return RedirectToAction("GetAll");
            }

            ViewBag.StaffId = new SelectList(db.Staffs, "Id", "Name", expense.StaffId);
            return View(expense);
        }

        // GET: Expenses/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Expense expense = db.Expenses.Find(id);
            if (expense == null)
            {
                return HttpNotFound();
            }
            ViewBag.StaffId = new SelectList(db.Staffs, "Id", "Name", expense.StaffId);
            return View(expense);
        }

        // POST: Expenses/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Description,Amount,DateTime,StaffId")] Expense expense)
        {
            if (ModelState.IsValid)
            {
                db.Entry(expense).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("GetAll");
            }
            ViewBag.StaffId = new SelectList(db.Staffs, "Id", "Name", expense.StaffId);
            return View(expense);
        }

        // GET: Expenses/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Expense expense = db.Expenses.Find(id);
            if (expense == null)
            {
                return HttpNotFound();
            }
            return View(expense);
        }

        // POST: Expenses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Expense expense = db.Expenses.Find(id);
            db.Expenses.Remove(expense);
            db.SaveChanges();
            return RedirectToAction("GetAll");
        }

        // GET: Expenses/Search
        public ActionResult Search()
        {
            return View();
        }

        // POST: Expenses/Search
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Search([Bind(Include = "Id,Description,Amount,DateTime,StaffId")] Expense expense)
        {


            IEnumerable<Expense> expenses;
            if (ModelState.IsValid)
            {

                expenses = from r in db.Expenses.AsQueryable()
                              where r.DateTime.Month == expense.DateTime.Month && r.Description.Contains(expense.Description)
                           select r;



                return View("GetAll", expenses);
            }

            
            return View(expense);
        }
















        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EducationSystemKZ/EducationSystemKZ_Azure/Controllers/ReportsController.cs
using EducationSystemKZ_Azure.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EducationSystemKZ_Azure.Controllers
{
    public class ReportsController : Controller
    {

        private zheminDBEntities db = new zheminDBEntities();


        // GET: Reports
        public ActionResult Index()
        {
            return View();
        }



        // GET: Reports/Monthly
        public ActionResult Monthly()
        {
            return View();
        }

        // POST: Reports/Monthly
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Monthly([Bind(Include = "Period,TotalFeeReceived,TotalExpenses,Salary,ElectricityFee,WaterFee,OtherFee")] Report report)
        {

            IEnumerable<decimal> tuitionFees;
            IEnumerable<Expense> expenses;
            IEnumerable<decimal> salaries;
            IEnumerable<decimal> otherFees;

            decimal sumTuitionFee = new decimal();
            decimal sumExpenses = new decimal();
            decimal sumSalary = new decimal();
            decimal sumOtherFee = new decimal();

            if (ModelState.IsValid)
            {
                tuitionFees = from r in db.TuitionFees.AsQueryable()
                              where r.DateTime.Month == report.Period.Month
                              select r.Amount;

                sumTuitionFee = tuitionFees.Sum();

                expenses = from r in db.Expenses.AsQueryable()
                              where r.DateTime.Month == report.Period.Month
                              select r;

                foreach (Expense e in expenses)
                {
                    sumExpenses += e.Amount;
                }

                salaries = from r in expenses
                            where r.Description == "salary"
                           select r.Amount;

                sumSalary = salaries.Sum();

                otherFees = from r in expenses
                                  where r.Description != "salary"
                            select r.Amount;

                sumOtherFee = otherFees.Sum();


                Report result = new Report() { Period = report.Period, TotalFeeReceived = sumTuitionFee, TotalExpenses = sumExpenses, Salary = sumSalary, OtherFee = sumOtherFee };
                return View("GetReport", result);
            }
            return View(report);

            

        }



        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

    }
}

EducationSystemKZ/EducationSystemKZ_Azure/Controllers/StaffsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EducationSystemKZ_Azure.Models;

namespace EducationSystemKZ_Azure.Controllers
{
    public class StaffsController : Controller
    {
        private zheminDBEntities db = new zheminDBEntities();

        // Index
        public ActionResult Index()
        {
            return View();
        }

        // GET: Staffs
        public ActionResult GetAll()
        {
            return View(db.Staffs.ToList());
        }

        // GET: Staffs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Staff staff = db.Staffs.Find(id);
            if (staff == null)
            {
                return HttpNotFound();
            }
            return View(staff);
        }

        // GET: Staffs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Staffs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,ContactNo,JobTitle")] Staff staff)
        {
            if (ModelState.IsValid)
            {
                db.Staffs.Add(staff);
                db.SaveChanges();
                return RedirectToAction("GetAll");
            }

            return View(staff);
        }

        // GET: Staffs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Staff staff = db.Staffs.Find(id);
            if (staff == null)
            {
                return HttpNotFound();
            }
            return View(staff);
        }

        // POST: Staffs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,ContactNo,JobTitle")] Staff staff)
        {
            if (ModelState.IsValid)
            {
                db.Entry(staff).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("GetAll");
            }
            return View(staff);
        }

        // GET: Staffs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Staff staff = db.Staffs.Find(id);
            if (staff == null)
            {
                return HttpNotFound();
            }
            return View(staff);
        }

        // POST: Staffs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Staff staff = db.Staffs.Find(id);
            db.Staffs.Remove(staff);
            db.SaveChanges();
            return RedirectToAction("GetAll");
        }


        // GET: Staffs/Search
        public ActionResult Search()
        {
            return View();
        }

        // POST: Staffs/Search
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Search([Bind(Include = "Id,Name,ContactNo,JobTitle")] Staff staff)
        {
            if (staff.Name == null)
            {
                staff.Name = "";
            }
            if (staff.JobTitle == null)
            {
                staff.JobTitle = "";
            }
            
            IEnumerable<Staff> staffs;
            if (ModelState.IsValid)
            {
                staffs = from r in db.Staffs.AsQueryable()
                           where r.Name.Contains(staff.Name) && r.JobTitle.Contains(staff.JobTitle)
                           select r;

                return View("GetAll", staffs);
            }
            return View(staff);

        }











        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EducationSystemKZ/EducationSystemKZ_Azure/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Ghazi Amanullah Khan Medical Institute</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
    <script type = 'text/javascript' >
        var appInsights=window.appInsights||function(config)
        {
            function r(config){ t[config] = function(){ var i = arguments; t.queue.push(function(){ t[config].apply(t, i)})} }
            var t = { config:config},u=document,e=window,o='script',s=u.createElement(o),i,f;for(s.src=config.url||'//az416426.vo.msecnd.net/scripts/a/ai.0.js',u.getElementsByTagName(o)[0].parentNode.appendChild(s),t.cookie=u.cookie,t.queue=[],i=['Event','Exception','Metric','PageView','Trace','Ajax'];i.length;)r('track'+i.pop());return r('setAuthenticatedUserContext'),r('clearAuthenticatedUserContext'),config.disableExceptionTracking||(i='onerror',r('_'+i),f=e[i],e[i]=function(config, r, u, e, o) { var s = f && f(config, r, u, e, o); return s !== !0 && t['_' + i](config, r, u, e, o),s}),t
        }({
            instrumentationKey:'4b332d57-430a-41f2-b410-1259226343d9'
        });
        
        window.appInsights=appInsights;
        appInsights.trackPageView();
    </script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="/" class="navbar-brand"><i class="fas fa-user-graduate"></i> GhaziAmanullahKhan</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Student", "Index", "Students")</li>
                    <li>@Html.ActionLink("Tution Fee", "Index", "TuitionFees")</li>
                    <li>@Html.ActionLink("Staff", "Index", "Staffs")</li>
                    <li>@Html.ActionLink("Expense", "Index", "Expenses")</li>
                    <li>@Html.ActionLink("Report", "Index", "Reports")</li>
                    <li>@Html.ActionLink("Scholarship", "NotYet", "Home")</li>
                    <li>@Html.ActionLink("Administrator", "Index", "Administrators")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li class="Logout"><a href="@Url.Action("LogOut","Login")"><i class="fas fa-door-open"></i> LogOut</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>